server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skarabeiy/config-repo
          username: skarabeiy
#          TODO
          password: GITHUB_PERSONAL_ACCESS_TOKEN
          default-label: main
  application:
    name: config-server